#!/usr/bin/env python3
"""Run mini-swe-agent non-interactively for one ai-lives session."""

from __future__ import annotations

import argparse
import os
import sys
import tomllib
from pathlib import Path
from typing import Any


DEFAULT_SETTINGS = {
    "model": "openai/your-model-name",
    "custom_llm_provider": "openai",
    "cost_tracking": "ignore_errors",
    "step_limit": 50,
    "cost_limit": 0.0,
    "command_timeout_seconds": 60,
    "output_path": "logs/mini-swe-agent-last-run.json",
}


def read_settings(path: Path) -> dict[str, Any]:
    if not path.exists():
        return dict(DEFAULT_SETTINGS)

    data = tomllib.loads(path.read_text(encoding="utf-8"))
    settings = dict(DEFAULT_SETTINGS)
    settings.update(data.get("mini_swe_agent", {}))
    return settings


def require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Environment variable {name} is required")
    return value


def build_model_kwargs(settings: dict[str, Any]) -> dict[str, Any]:
    return {
        "custom_llm_provider": settings["custom_llm_provider"],
        "api_base": require_env("AI_BASE_URL"),
        "api_key": require_env("AI_API_KEY"),
        "drop_params": True,
    }


def read_task(prompt_file: Path) -> str:
    if not prompt_file.exists():
        raise RuntimeError(f"Prompt file does not exist: {prompt_file}")
    return prompt_file.read_text(encoding="utf-8")


def run_agent(root: Path, prompt_file: Path, settings_path: Path) -> int:
    from minisweagent.agents.default import DefaultAgent
    from minisweagent.environments.local import LocalEnvironment
    from minisweagent.models.litellm_model import LitellmModel

    settings = read_settings(settings_path)
    task = read_task(prompt_file)
    output_path = root / str(settings["output_path"])

    model = LitellmModel(
        model_name=require_env("AI_MODEL"),
        model_kwargs=build_model_kwargs(settings),
        cost_tracking=str(settings["cost_tracking"]),
    )
    env = LocalEnvironment(
        cwd=str(root),
        timeout=int(settings["command_timeout_seconds"]),
        env={
            "PAGER": "cat",
            "MANPAGER": "cat",
            "LESS": "-R",
            "PIP_PROGRESS_BAR": "off",
            "TQDM_DISABLE": "1",
        },
    )
    agent = DefaultAgent(
        model,
        env,
        system_template="You are a careful autonomous software engineering agent.",
        instance_template=(
            "{{task}}\n\n"
            "When the session work is complete, finish by executing exactly this command:\n"
            "echo COMPLETE_TASK_AND_SUBMIT_FINAL_OUTPUT\n"
            "Do not combine that command with anything else."
        ),
        step_limit=int(settings["step_limit"]),
        cost_limit=float(settings["cost_limit"]),
        output_path=output_path,
    )
    result = agent.run(task)
    return 0 if result.get("exit_status") == "Submitted" else 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run mini-swe-agent for one ai-lives session.")
    parser.add_argument("--root", required=True, help="Session worktree root.")
    parser.add_argument("--prompt-file", required=True, help="Prompt file generated by run_session.py.")
    parser.add_argument(
        "--settings",
        default="config/project.toml",
        help="Project settings path, relative to --root unless absolute.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    prompt_file = Path(args.prompt_file)
    if not prompt_file.is_absolute():
        prompt_file = root / prompt_file
    settings_path = Path(args.settings)
    if not settings_path.is_absolute():
        settings_path = root / settings_path

    try:
        return run_agent(root, prompt_file, settings_path)
    except Exception as exc:
        print(f"mini-swe-agent session failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())